### PR TITLE
Neta DAO Proposal: Balanced Validator Set and Tokenomics for AtomOne

### PR DESCRIPTION
**Pull request by cosmonought**
This is our proposal for the All in Bits Grants and Bounties program, focused on Validator Selection and Crypto-Economics.

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
Hi @cosmonought - Thank you for your grant application. We are looking into your proposal in more detail and will get back to you.

**Comment by VT-Cosmos** [comment]
Hi @cosmonought 
After the initial review of your proposal, we have the following questions: 
- What are the overlapping features of the work you did for Juno, with the one your team plans to deliver for AtomOne?
- Have you had any previous experience working with ICS?
- Regarding the objective of Phase 1: Apart from the existing validator selection in Cosmos, are you able to provide insight into other validator selection systems from other ecosystems so that it is incorporated in the work you plan for phase 2?
- How do you intend to address the crypto economic challenges that arises from the new parameterization with the new potential validator system?

**Comment by cosmonought** [comment]
Hi @VT-Cosmos, thank you for reaching out.

1) In the context of this grant application, I don't believe there is really any overlap with the work done on Juno. The Juno Charter was an organizational/operational document that attempted to structure Juno's operations in a manner that honored the principles of transparency, accountability, and community participation. It was primarily a document governing the creation and operation of Juno subDAOs, whereas (as I understand it) this grant is really thinking about the validator system and tokenomic models. 

Addendum: I (Lil D) organized and led the Juno Charter calls for ~15 weeks, but the Juno Charter was ultimately the creation of many participants; I would direct you to the Neta DAO Constitution if you are interested in an example of my work where I was the primary author, and I think you will see a marked difference between it and the Charter. Still, I do not believe there is much direct overlap between these efforts and the grant application, but I do carry the knowledge and insights I've gained from this work to my feedback on the AtomOne Constitution.

2) I am not a developer, so I do not have work experience with ICS. I understand the concept as an end-user and am still reviewing the linked resources on it from the grants page, but one of the priorities of our work during the grant would be diving into these details and talking with the AiB and AtomOne teams to better understand ICS (and AtomOne's proposed/desired changes to it). One 'basic' question I know I have already is that GnoLand plans to be an ICS consumer from AtomOne, but I don't know how GnoLand's Proof of Contribution system interacts with ICS. Long-term I would like to get better acquainted with all the technical details and learn some Go/Gno of my own. I will add that Poroburu has more knowledge in this realm than I do, so I hope I have not embarrassed my team with this response.

3) Yes. Of course the ultimate shape and emphases of the research phase will depend on the conversations we have with AiB and AtomOne communities, but the comparative study of block validation in Proof of Work, Proof of Authority, etc. helps illuminate what is possible. I would be especially interested to compare variations on proof of stake, such as Nominated Proof of Stake, Proof of Importance, and so on. Additionally, many challenges and issues that arise from the validator system are not necessarily unique to blockchain, so structural lessons can be gleaned from studies of distributed organizations that are commercial, political, or 'human interest' in nature, and some of the research phase would include surveying this broader research tradition (sometimes known as "Institutional and Organizational Analysis"). Some scholars, such as Ellie Rennie and Eric Alston, are already attempting to bridge these two areas, e.g., https://deepcast.fm/episode/410/mint-burn-episode-48-the-validator-commons-live-w-ellie-rennie-eric-alston-and-kelsie-nabben

4) Every incentive system is at a root a game of margins: every rule/parameter is going to create marginal trade-offs that drive network participants' behavior. Since network participants come in several 'buckets'—non-staked token holders, stakers, validators, independent developers, foundations or companies, and sometimes large investors or other entities—the challenge of designing a tokenomic system is balancing trade-offs between these buckets of participants to keep 'the game' engaging for everyone (within the community's defined margins) without necessarily creating runaway winners or other unwanted system behavior. Our goal is to provide one or more tokenomic models in terms of the margins and trade-offs that are entailed, and we hope to work with AiB and AtomOne to guide and refine our understanding of desired behaviors and outcomes as we progress.

Please let me know if anything is unclear or needs further elaboration. We are also happy to schedule a call so you can hear from all three of us on these or any other issues.

Thank you again and have a great weekend!

**Comment by VT-Cosmos** [comment]
Thank you. We will get back to you shortly.

**Pull request closed without merging**
