### PR TITLE
OrbitLabs _Tendermint2 grant

### PR DESCRIPTION
**Pull request by TropicalDog17**

### CODE REVIEW

**Comment by VT-Cosmos** [comment]
@TropicalDog17 Thank you for your grant application. We are looking into your proposal in more detail and will get back to you shortly.

**Comment by VT-Cosmos** [comment]
Hi @TropicalDog17 
After the initial review of your proposal, we have the following questions:
- Can you list the link to PRs on your previous contribution to the relevant areas of the grant you are applying for (i.e. previous contribution to consensus, etc)?
- Based on your proposal, how many hours per week is your team going to spend working on the grant (estimate is sufficient)?
Thank you for your response,

**Comment by TropicalDog17** [comment]
Thank you for reviewing our proposal @VT-Cosmos. Regarding your questions:

Here are links to some of our previous contributions relevant to the areas of the grant we're applying for:

1. Consensus-related work:
   - [CometBFT PR #2792](https://github.com/cometbft/cometbft/pull/2792)
   - [Celestia Core PR #1321](https://github.com/celestiaorg/celestia-core/pull/1321)

2. Core protocol development:
   - [Reth PR #9044](https://github.com/paradigmxyz/reth/pull/9044)
   - [Cosmos SDK PR #20161](https://github.com/cosmos/cosmos-sdk/pull/20161)
   - [Cosmos SDK PR #20354](https://github.com/cosmos/cosmos-sdk/pull/20354)
   - [Cosmos SDK PR #20404](https://github.com/cosmos/cosmos-sdk/pull/20404)

3. Blockchain infrastructure:
   - [Astra Protocol commits](https://github.com/AstraProtocol/astra/commits/astra/?author=hoanguyenkh)
   - [Osmosis Fee Abstraction commits - Tuan Tran](https://github.com/osmosis-labs/fee-abstraction/commits/main/?author=tuantran1702)
   - [Osmosis Fee Abstraction - Tien Nguyen)](https://github.com/osmosis-labs/fee-abstraction/commits/main/?author=tnv1)
   - [IBC-Go PRs by Tuan Tran](https://github.com/cosmos/ibc-go/pulls?q=is%3Apr+author%3ATropicalDog17+is%3Aclosed)
   - [Composable Cosmos PRs by hoank101](https://github.com/ComposableFi/composable-cosmos/pulls?q=is%3Apr+is%3Aclosed+author%3Ahoank101)
   - [BeaconKit PRs by Tuan Tran](https://github.com/berachain/beacon-kit/pulls?q=is%3Apr+author%3ATropicalDog17+is%3Aclosed)
   - [BeaconKit PRss by Khanh Hoa](https://github.com/berachain/beacon-kit/pulls?q=is%3Apr+author%3Ahoank101+is%3Aclosed)

We'd like to mention that we all were previously employed by Notional and have worked on various issues in the blockchain space. While our presence in the open source ecosystem is not quite extensive, we have significant experience in software engineering.

For a more comprehensive review of our background and expertise, we have sent our CVs to your email(grants@allinbits.com).

Please let us know if you need any further information or clarification.

**Comment by VT-Cosmos** [comment]
The feedback regarding this application has been provided.

**Pull request closed without merging**
